# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0014_auto_20160628_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(),
        ),
    ]
